import NavLinks from "@/components/nav-links/nav-links"
import './styles.css'

export const metadata = {
  title: {
    default: 'Default Title',
    template: '%s | My Site'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const navLinks = [
    { name: 'Register', href: '/register' },
    { name: 'Login', href: '/login' },
    { name: 'Blogs', href: '/blogs' }
  ]

  return (
    <html lang="en">
      <body>
        <header>
          <p>This is Header</p>
        </header>
        <NavLinks
          navLinks={navLinks}
        ></NavLinks>
        {children}
        <footer>
          <p>This is Footer</p>
        </footer>
      </body>
    </html>
  )
}
